from __future__ import annotations

from typing import Any

KNOWLEDGE_TAXONOMY_SEED_ROWS: list[dict[str, Any]] = [
    # block_type level 1
    {
        "dimension": "block_type",
        "code": "qualification_document",
        "parent_code": None,
        "label": "资质文件",
        "label_en": None,
        "level": 1,
        "sort_order": 10,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "qualification_sub_brand",
        "parent_code": "qualification_document",
        "label": "子品牌",
        "label_en": None,
        "level": 2,
        "sort_order": 11,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "qualification_headquarters",
        "parent_code": "qualification_document",
        "label": "总公司",
        "label_en": None,
        "level": 2,
        "sort_order": 12,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "qualification_branch",
        "parent_code": "qualification_document",
        "label": "分公司",
        "label_en": None,
        "level": 2,
        "sort_order": 13,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "financial_qualification",
        "parent_code": None,
        "label": "财务资质",
        "label_en": None,
        "level": 1,
        "sort_order": 20,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "awards_honors",
        "parent_code": None,
        "label": "获奖及荣誉材料",
        "label_en": None,
        "level": 1,
        "sort_order": 30,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "intellectual_property",
        "parent_code": None,
        "label": "知识产权",
        "label_en": None,
        "level": 1,
        "sort_order": 40,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "ip_software_copyright",
        "parent_code": "intellectual_property",
        "label": "软著",
        "label_en": None,
        "level": 2,
        "sort_order": 41,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "ip_patent",
        "parent_code": "intellectual_property",
        "label": "专利证书",
        "label_en": None,
        "level": 2,
        "sort_order": 42,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "ip_trademark",
        "parent_code": "intellectual_property",
        "label": "商标证书",
        "label_en": None,
        "level": 2,
        "sort_order": 43,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "company_intro",
        "parent_code": None,
        "label": "企业介绍",
        "label_en": None,
        "level": 1,
        "sort_order": 50,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "company_product_intro",
        "parent_code": "company_intro",
        "label": "企业产品介绍",
        "label_en": None,
        "level": 2,
        "sort_order": 51,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "company_history",
        "parent_code": "company_intro",
        "label": "发展历程",
        "label_en": None,
        "level": 2,
        "sort_order": 52,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "company_org_structure",
        "parent_code": "company_intro",
        "label": "组织架构",
        "label_en": None,
        "level": 2,
        "sort_order": 53,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "member_info",
        "parent_code": None,
        "label": "成员信息",
        "label_en": None,
        "level": 1,
        "sort_order": 60,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "member_tech_team",
        "parent_code": "member_info",
        "label": "技术团队",
        "label_en": None,
        "level": 2,
        "sort_order": 61,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "member_product_team",
        "parent_code": "member_info",
        "label": "产品团队",
        "label_en": None,
        "level": 2,
        "sort_order": 62,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "member_service_team",
        "parent_code": "member_info",
        "label": "服务团队",
        "label_en": None,
        "level": 2,
        "sort_order": 63,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "official_template",
        "parent_code": None,
        "label": "官方模版",
        "label_en": None,
        "level": 1,
        "sort_order": 70,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "block_type",
        "code": "product_solution",
        "parent_code": None,
        "label": "产品方案知识",
        "label_en": None,
        "level": 1,
        "sort_order": 80,
        "is_active": True,
        "metadata": {},
    },
    # application_type
    {
        "dimension": "application_type",
        "code": "fixed_reference",
        "parent_code": None,
        "label": "固定引用",
        "label_en": None,
        "level": 1,
        "sort_order": 10,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "application_type",
        "code": "preferred_reference",
        "parent_code": None,
        "label": "优先引用",
        "label_en": None,
        "level": 1,
        "sort_order": 20,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "application_type",
        "code": "composite_generation",
        "parent_code": None,
        "label": "综合生成",
        "label_en": None,
        "level": 1,
        "sort_order": 30,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "application_type",
        "code": "template_fill",
        "parent_code": None,
        "label": "模版填充",
        "label_en": None,
        "level": 1,
        "sort_order": 40,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "application_type",
        "code": "reference_rewrite",
        "parent_code": None,
        "label": "参考改写",
        "label_en": None,
        "level": 1,
        "sort_order": 50,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "application_type",
        "code": "fact_extraction",
        "parent_code": None,
        "label": "事实提取",
        "label_en": None,
        "level": 1,
        "sort_order": 60,
        "is_active": True,
        "metadata": {},
    },
    # business_line
    {
        "dimension": "business_line",
        "code": "general",
        "parent_code": None,
        "label": "通用",
        "label_en": None,
        "level": 1,
        "sort_order": 10,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "meal_subsidy",
        "parent_code": None,
        "label": "餐补",
        "label_en": None,
        "level": 1,
        "sort_order": 20,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "insurance",
        "parent_code": None,
        "label": "保险",
        "label_en": None,
        "level": 1,
        "sort_order": 30,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "gift_package",
        "parent_code": None,
        "label": "超级礼包/礼包",
        "label_en": None,
        "level": 1,
        "sort_order": 40,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "health_check",
        "parent_code": None,
        "label": "体检",
        "label_en": None,
        "level": 1,
        "sort_order": 50,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "birthday",
        "parent_code": None,
        "label": "生日",
        "label_en": None,
        "level": 1,
        "sort_order": 60,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "movie",
        "parent_code": None,
        "label": "电影",
        "label_en": None,
        "level": 1,
        "sort_order": 70,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "procurement",
        "parent_code": None,
        "label": "物资采购",
        "label_en": None,
        "level": 1,
        "sort_order": 80,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "baifude",
        "parent_code": None,
        "label": "百福得",
        "label_en": None,
        "level": 1,
        "sort_order": 90,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "business_line",
        "code": "lefu_card",
        "parent_code": None,
        "label": "乐福卡",
        "label_en": None,
        "level": 1,
        "sort_order": 100,
        "is_active": True,
        "metadata": {},
    },
    # dynamic_type
    {
        "dimension": "dynamic_type",
        "code": "brand_authorization",
        "parent_code": None,
        "label": "品牌授权信息",
        "label_en": None,
        "level": 1,
        "sort_order": 10,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "dynamic_type",
        "code": "store_info",
        "parent_code": None,
        "label": "门店信息",
        "label_en": None,
        "level": 1,
        "sort_order": 20,
        "is_active": True,
        "metadata": {},
    },
    {
        "dimension": "dynamic_type",
        "code": "supplier_info",
        "parent_code": None,
        "label": "供应商信息",
        "label_en": None,
        "level": 1,
        "sort_order": 30,
        "is_active": True,
        "metadata": {},
    },
]
